[package]
name = "health"
version = "0.1.0"
edition = "2021"

[dependencies]
vercel_runtime = "1.1.0"
tokio = { version = "1.0", features = ["macros"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[lib]
name = "health"
crate-type = ["cdylib"]